"""V4 Pydantic schemas — the Gold Standard definition.

These models define the structured output that Gemini must produce.
They also serve as the validation layer for the LLM response.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class QuestionV4(BaseModel):
    """A single worksheet question generated by the LLM."""

    id: int = Field(description="Question number, starting from 1")
    question_type: str = Field(
        description="One of: MCQ, True/False, FillBlank, ShortAnswer, ErrorDetection, WordProblem"
    )
    text: str = Field(description="The question text. For FillBlank, include exactly one '______'.")
    options: list[str] | None = Field(
        default=None,
        description="Exactly 4 options for MCQ. Must include the correct answer. null for other types.",
    )
    answer: str = Field(description="The correct answer. For MCQ, must be one of the options.")
    explanation: str = Field(description="Brief, parent-friendly explanation of how to solve this question.")
    hint: str | None = Field(
        default=None,
        description="A helpful hint that does NOT reveal the answer.",
    )
    learning_goal_tag: str = Field(
        description="Which specific learning goal from the curriculum map this question tests."
    )
    difficulty: str = Field(description="One of: Easy, Medium, Hard")
    skill_tag: str | None = Field(
        default=None,
        description="Specific skill being tested (e.g., 'identify_shapes', 'add_with_carry').",
    )


class WorksheetV4(BaseModel):
    """A complete worksheet generated by the LLM."""

    title: str = Field(description="A clear, descriptive worksheet title.")
    class_level: int = Field(description="Class number (1-5)")
    subject: str
    topic: str
    learning_goals: list[str] = Field(description="List of 2-3 learning goals this worksheet covers.")
    questions: list[QuestionV4]
    common_mistake: str = Field(description="One common mistake students make on this topic.")
    parent_guide: str = Field(description="A 2-3 sentence tip for parents on how to support this lesson at home.")
