"""Context pools for worksheet variety — names, scenarios, rotation."""

import random

INDIAN_NAMES = [
    # North Indian
    "Aarav", "Ananya", "Vihaan", "Diya", "Reyansh", "Saanvi", "Arjun", "Isha",
    "Kabir", "Myra", "Aditya", "Kiara", "Rohan", "Priya", "Vivaan", "Anika",
    # South Indian
    "Karthik", "Lakshmi", "Surya", "Meenakshi", "Harish", "Divya", "Pranav", "Anjali",
    # East Indian
    "Sourav", "Riya", "Arnab", "Moushumi", "Subham", "Shreya",
    # West Indian
    "Mihir", "Nandini", "Parth", "Rupal", "Darshan", "Riddhi", "Jay", "Mira",
    # Universal
    "Krishna", "Zara", "Rudra", "Pari", "Atharv", "Navya", "Shaurya", "Aadhya",
    "Dhruv", "Sara", "Arnav", "Anvi", "Ishan", "Tara", "Kian", "Meera",
    "Yash", "Nisha", "Aryan", "Siya", "Neil", "Pooja", "Manav", "Kavya",
    "Sameer", "Tanvi", "Kunal", "Ritika", "Dev", "Sneha", "Rahul", "Trisha",
    "Om", "Gauri", "Ved", "Aditi", "Ayan", "Sana", "Rehan", "Keerthi",
]  # fmt: skip

FEMALE_NAMES = {
    "Ananya", "Diya", "Saanvi", "Isha", "Myra", "Kiara", "Priya", "Anika",
    "Zara", "Pari", "Navya", "Aadhya", "Riya", "Sara", "Anvi", "Tara",
    "Meera", "Nisha", "Siya", "Pooja", "Sneha", "Kavya", "Tanvi", "Ritika",
    "Lakshmi", "Meenakshi", "Divya", "Anjali", "Moushumi", "Shreya",
    "Nandini", "Rupal", "Riddhi", "Mira", "Trisha", "Gauri", "Aditi",
    "Sana", "Keerthi",
}  # fmt: skip

CONTEXT_POOLS = {
    "Maths": [
        "shopping at mandi",
        "cooking at home",
        "sports day at school",
        "Diwali celebration",
        "train journey",
        "zoo visit",
        "birthday party",
        "garden planting",
        "classroom activity",
        "Holi festival",
        "bus ride to school",
        "library visit",
        "cricket match",
        "picnic in park",
        "temple fair",
        "school canteen",
        "post office visit",
        "railway station",
        "Raksha Bandhan",
        "kite flying on Makar Sankranti",
        "Republic Day parade",
        "farmer's field",
        "fruit seller's cart",
        "school annual day",
        "monsoon season",
    ],
    "English": [
        "school classroom",
        "family dinner",
        "park visit",
        "birthday party",
        "rainy day at home",
        "school assembly",
        "market shopping",
        "bus journey",
        "story time",
        "letter writing",
        "playground",
        "library",
        "school picnic",
        "grandparents' house",
        "morning routine",
        "pet care",
        "hobby class",
        "nature walk",
    ],
    "EVS": [
        "kitchen at home",
        "school garden",
        "neighborhood walk",
        "rainy day",
        "summer vacation",
        "market visit",
        "farm visit",
        "river bank",
        "village fair",
        "forest walk",
        "rooftop garden",
        "school field trip",
        "water tank area",
        "bird sanctuary",
        "recycling center",
        "morning assembly",
        "monsoon puddles",
        "winter morning",
    ],
    "Science": [
        "science lab",
        "kitchen experiment",
        "garden observation",
        "nature walk",
        "weather observation",
        "home kitchen",
        "school playground",
        "farm visit",
        "hospital visit",
        "water treatment plant",
        "bird watching",
        "night sky",
        "aquarium visit",
        "science fair",
        "terrace garden",
        "morning walk",
        "river bank",
        "school canteen",
    ],
    "Hindi": [
        "घर पर",
        "बाज़ार में",
        "विद्यालय में",
        "पार्क में",
        "रेलगाड़ी में",
        "मेला",
        "त्योहार",
        "रसोई में",
        "बगीचे में",
        "पुस्तकालय",
        "खेल का मैदान",
        "गाँव में",
        "मंदिर में",
        "नदी के किनारे",
        "सुबह की सैर",
        "चिड़ियाघर में",
        "डाकघर में",
        "अस्पताल में",
    ],
    "GK": [
        "world tour",
        "museum visit",
        "map reading",
        "quiz competition",
        "newspaper reading",
        "documentary",
        "school exhibition",
        "history walk",
        "globe study",
        "current affairs",
        "national park visit",
        "space center",
        "parliament house",
        "folk festival",
        "science museum",
        "cultural fair",
        "heritage site",
        "sports arena",
    ],
    "Computer": [
        "computer lab",
        "home desktop",
        "school office",
        "gaming session",
        "internet browsing",
        "typing class",
        "coding club",
        "digital art class",
        "online research",
        "email writing",
        "school presentation",
        "robotics club",
        "animation studio",
        "data entry",
        "school library",
        "tech fair",
        "smart classroom",
        "video call",
    ],
    "Health": [
        "morning routine",
        "school sports",
        "lunch break",
        "doctor visit",
        "yoga class",
        "playground",
        "swimming pool",
        "dance class",
        "school canteen",
        "hand washing station",
        "dental checkup",
        "first aid class",
        "meditation session",
        "eye checkup",
        "school health camp",
        "nutrition class",
        "hygiene day",
        "sports day",
    ],
    "Moral Science": [
        "school bus",
        "classroom sharing",
        "playground dispute",
        "helping at home",
        "new student in class",
        "festival celebration",
        "community service",
        "animal rescue",
        "elder care",
        "honesty test",
        "teamwork activity",
        "environment day",
        "kindness week",
        "lost and found",
        "sharing lunch",
        "helping a friend",
        "cleaning campaign",
        "charity event",
    ],
}

# Objects for maths word problems (per grade context)
MATHS_OBJECTS = {
    "1": [
        "apples",
        "mangoes",
        "books",
        "crayons",
        "marbles",
        "pencils",
        "flowers",
        "chocolates",
        "balloons",
        "stickers",
        "laddoos",
        "bananas",
        "cookies",
        "toy cars",
        "ribbons",
        "beads",
        "shells",
        "leaves",
        "stars",
        "buttons",
    ],
    "2": [
        "stamps",
        "stickers",
        "marbles",
        "books",
        "beads",
        "coins",
        "flowers",
        "cards",
        "shells",
        "stars",
        "seeds",
        "blocks",
        "badges",
        "tickets",
        "postcards",
        "pebbles",
        "ribbons",
        "feathers",
        "buttons",
        "erasers",
    ],
    "3": [
        "notebooks",
        "pencils",
        "rupees",
        "stickers",
        "pages",
        "students",
        "toys",
        "packets",
        "laddoos",
        "bangles",
        "candles",
        "diyas",
        "envelopes",
        "stamps",
        "bookmarks",
        "charts",
        "maps",
        "posters",
        "badges",
        "certificates",
    ],
    "4": [
        "metres",
        "kilometres",
        "kilograms",
        "litres",
        "rupees",
        "pages",
        "tickets",
        "boxes",
        "bottles",
        "packets",
        "minutes",
        "hours",
        "degrees",
        "centimetres",
        "grams",
        "millilitres",
        "passengers",
        "workers",
        "students",
        "trees",
    ],
    "5": [
        "kilometres",
        "kilograms",
        "litres",
        "rupees",
        "hours",
        "minutes",
        "metres",
        "grams",
        "millilitres",
        "students",
        "tickets",
        "books",
        "packets",
        "bottles",
        "boxes",
        "workers",
        "passengers",
        "trees",
        "marks",
        "coins",
    ],
}

# Word problem frame templates for question variety
WORD_PROBLEM_FRAMES = {
    "addition": [
        "{name} has {a} {obj}. {name2} gives {pronoun} {b} more. How many {obj} does {name} have now?",
        "There are {a} {obj} in one basket and {b} {obj} in another. How many {obj} are there altogether?",
        "{name} counted {a} {obj} in the morning and {b} {obj} in the evening. What is the total?",
        "First, {name} collected {a} {obj}. Then {name} found {b} more. How many {obj} in all?",
        "{name} and {name2} are counting {obj}. {name} counts {a} and {name2} counts {b}. How many together?",
        "On Monday {name} had {a} {obj}. On Tuesday {pronoun} got {b} more. How many by Tuesday?",
        "{a} {obj} are on the shelf. {name} puts {b} more. How many {obj} on the shelf now?",
        "At the {context}, {name} saw {a} {obj} and then {b} more came. How many in total?",
    ],
    "subtraction": [
        "{name} had {a} {obj}. {pronoun_cap} gave {b} to {name2}. How many {obj} are left?",
        "There were {a} {obj}. {b} were taken away. How many remain?",
        "{name} started with {a} {obj}. After giving away {b}, how many are left?",
        "Out of {a} {obj}, {name} used {b}. How many {obj} does {name} still have?",
        "{a} {obj} were on the table. {name} took {b}. How many are still on the table?",
        "In the morning there were {a} {obj}. By evening, {b} had gone. How many left?",
        "{name} bought {a} {obj} from the {context}. {pronoun_cap} ate {b}. How many uneaten?",
    ],
    "multiplication": [
        "There are {a} rows of {obj}. Each row has {b} {obj}. How many {obj} in total?",
        "{name} has {a} bags. Each bag has {b} {obj}. How many {obj} altogether?",
        "If {name} gets {b} {obj} every day for {a} days, how many {obj} in all?",
        "Each of {a} children has {b} {obj}. How many {obj} do they have together?",
    ],
    "fractions": [
        "{name} has {a} {obj}. {pronoun_cap} eats half of them. How many did {pronoun} eat?",
        "A {obj} is cut into {b} equal pieces. {name} takes 1 piece. What fraction did {name} take?",
        "{name} shared {a} {obj} equally among {b} friends. How many did each friend get?",
    ],
}


def pick_names(count: int, exclude: list[str] | None = None) -> list[str]:
    """Pick N unique Indian names, excluding any already used."""
    available = [n for n in INDIAN_NAMES if n not in (exclude or [])]
    return random.sample(available, min(count, len(available)))


def pick_contexts(subject: str, count: int, generation_offset: int = 0) -> list[str]:
    """Pick N contexts with rotation for variety across worksheets."""
    pool = CONTEXT_POOLS.get(subject, CONTEXT_POOLS["Maths"])
    start = (generation_offset * count) % len(pool)
    return [pool[(start + i) % len(pool)] for i in range(count)]


SCIENCE_OBJECTS = {
    "food": ["chapati", "rice", "dal", "milk", "fruits", "vegetables", "stomach", "teeth", "tongue", "saliva"],
    "digestion": ["chapati", "rice", "dal", "milk", "fruits", "vegetables", "stomach", "teeth", "tongue", "saliva"],
    "human body": ["bones", "muscles", "heart", "lungs", "brain", "blood", "skin", "eyes", "ears", "nose"],
    "body": ["bones", "muscles", "heart", "lungs", "brain", "blood", "skin", "eyes", "ears", "nose"],
    "plants": ["leaves", "roots", "stem", "flowers", "seeds", "fruits", "bark", "branches", "soil", "sunlight"],
    "animals": ["nests", "burrows", "feathers", "scales", "fur", "wings", "legs", "eggs", "milk", "food"],
    "water": ["rivers", "ponds", "wells", "taps", "rain", "ice", "steam", "clouds", "ocean", "lakes"],
    "air": ["wind", "oxygen", "balloons", "kites", "bubbles", "smoke", "dust", "fans", "lungs", "breathing"],
    "light": ["torch", "candle", "sun", "shadow", "mirror", "lamp", "bulb", "rainbow", "fire", "stars"],
    "force": ["push", "pull", "wheels", "ramps", "springs", "magnets", "gravity", "friction", "machines", "levers"],
    "default": [
        "things",
        "objects",
        "items",
        "samples",
        "examples",
        "parts",
        "materials",
        "types",
        "groups",
        "features",
    ],
}

EVS_OBJECTS = {
    "animals": [
        "birds",
        "fish",
        "insects",
        "pets",
        "wild animals",
        "farm animals",
        "nests",
        "eggs",
        "feathers",
        "food",
    ],
    "plants": ["trees", "flowers", "leaves", "seeds", "fruits", "vegetables", "roots", "garden", "forest", "grass"],
    "food": ["chapati", "rice", "dal", "sabzi", "fruits", "milk", "curd", "laddoo", "idli", "dosa"],
    "water": ["tap", "well", "river", "pond", "rain", "bucket", "glass", "bottle", "tank", "pipe"],
    "family": [
        "mother",
        "father",
        "grandparents",
        "siblings",
        "cousins",
        "neighbours",
        "friends",
        "teachers",
        "elders",
        "babies",
    ],
    "shelter": ["house", "hut", "tent", "flat", "bungalow", "rooms", "kitchen", "bathroom", "roof", "walls"],
    "senses": ["eyes", "ears", "nose", "tongue", "skin", "sounds", "smells", "tastes", "touch", "colours"],
    "weather": ["rain", "sun", "wind", "clouds", "snow", "fog", "rainbow", "thunder", "seasons", "temperature"],
    "default": [
        "things",
        "objects",
        "items",
        "examples",
        "types",
        "parts",
        "features",
        "groups",
        "activities",
        "places",
    ],
}

ENGLISH_OBJECTS = {
    "nouns": ["dog", "cat", "book", "school", "tree", "river", "teacher", "garden", "house", "ball"],
    "verbs": [
        "running",
        "jumping",
        "reading",
        "writing",
        "singing",
        "dancing",
        "cooking",
        "playing",
        "swimming",
        "drawing",
    ],
    "tenses": [
        "yesterday",
        "today",
        "tomorrow",
        "morning",
        "evening",
        "always",
        "sometimes",
        "never",
        "often",
        "usually",
    ],
    "default": [
        "words",
        "sentences",
        "stories",
        "letters",
        "paragraphs",
        "poems",
        "questions",
        "answers",
        "ideas",
        "examples",
    ],
}

HINDI_OBJECTS = {
    "varnamala": ["\u0905", "\u0906", "\u0907", "\u0908", "\u0909", "\u090a", "\u0915", "\u0916", "\u0917", "\u0918"],
    "shabd": [
        "\u091c\u0932",
        "\u092b\u0932",
        "\u0915\u0932",
        "\u0926\u0932",
        "\u092c\u0932",
        "\u091a\u0932",
        "\u092e\u0928",
        "\u0935\u0928",
        "\u0927\u0928",
        "\u091c\u0928",
    ],
    "vakya": [
        "\u0935\u093e\u0915\u094d\u092f",
        "\u0936\u092c\u094d\u0926",
        "\u0905\u0915\u094d\u0937\u0930",
        "\u092e\u093e\u0924\u094d\u0930\u093e",
        "\u091a\u093f\u0924\u094d\u0930",
        "\u0915\u0939\u093e\u0928\u0940",
        "\u0915\u0935\u093f\u0924\u093e",
        "\u0917\u0940\u0924",
        "\u092a\u0924\u094d\u0930",
        "\u0928\u093f\u092c\u0902\u0927",
    ],
    "default": [
        "\u0936\u092c\u094d\u0926",
        "\u0935\u093e\u0915\u094d\u092f",
        "\u091a\u093f\u0924\u094d\u0930",
        "\u0915\u0939\u093e\u0928\u0940",
        "\u0905\u0915\u094d\u0937\u0930",
        "\u092a\u0941\u0938\u094d\u0924\u0915",
        "\u0915\u0932\u092e",
        "\u0935\u093f\u0926\u094d\u092f\u093e\u0932\u092f",
        "\u092c\u091a\u094d\u091a\u0947",
        "\u0916\u093f\u0932\u094c\u0928\u0947",
    ],
}


def pick_objects(grade_num: int, count: int) -> list[str]:
    """Pick N maths word problem objects for this grade."""
    pool = MATHS_OBJECTS.get(str(grade_num), MATHS_OBJECTS["3"])
    return random.sample(pool, min(count, len(pool)))


def pick_subject_objects(subject: str, topic: str, count: int, grade_num: int) -> list[str]:
    """Pick context objects appropriate to the subject and topic."""
    subject_lower = subject.lower()
    topic_lower = topic.lower()

    pool_map = {
        "science": SCIENCE_OBJECTS,
        "evs": EVS_OBJECTS,
        "english": ENGLISH_OBJECTS,
        "hindi": HINDI_OBJECTS,
    }

    pool = pool_map.get(subject_lower)
    if pool:
        # Try topic-specific sub-pool
        for key, objects in pool.items():
            if key in topic_lower:
                return random.sample(objects, min(count, len(objects)))
        # Fallback to default for this subject
        default = pool.get("default", [])
        if default:
            return random.sample(default, min(count, len(default)))

    # Fallback to maths objects for grade
    return pick_objects(grade_num, count)
